## Exercises

All of the exercises are focused on practicing the code above.

You should be able to complete them by referencing each section or by following the resource(s) linked.

**Resources:**

* [Exercise template notebook for 00](https://github.com/mrdbourke/pytorch-deep-learning/blob/main/extras/exercises/00_pytorch_fundamentals_exercises.ipynb).
* [Example solutions notebook for 00](https://github.com/mrdbourke/pytorch-deep-learning/blob/main/extras/solutions/00_pytorch_fundamentals_exercise_solutions.ipynb) (try the exercises *before* looking at this).

1. Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor) and for [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).
2. Create a random tensor with shape `(7, 7)`.
3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).
4. Set the random seed to `0` and do exercises 2 & 3 over again.
5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one). If there is, set the GPU random seed to `1234`.
6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed).
7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
8. Find the maximum and minimum values of the output of 7.
9. Find the maximum and minimum index values of the output of 7.
10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

##### 1. Create a random tensor with shape (7, 7).

In [2]:
import torch

In [3]:
# Creating a random tensor with shape 7 by 7
random_tensor = torch.rand(size=(7,7))
random_tensor, random_tensor.dtype

(tensor([[0.0880, 0.6857, 0.2899, 0.0752, 0.5878, 0.1670, 0.2420],
         [0.0566, 0.9773, 0.4329, 0.5658, 0.9470, 0.0545, 0.9837],
         [0.5571, 0.8669, 0.0676, 0.2651, 0.5326, 0.5801, 0.2228],
         [0.9109, 0.9185, 0.6631, 0.5438, 0.0069, 0.1121, 0.6267],
         [0.2918, 0.1781, 0.9079, 0.3182, 0.2424, 0.5133, 0.2983],
         [0.3878, 0.3390, 0.6416, 0.7494, 0.6444, 0.6402, 0.5155],
         [0.2575, 0.5616, 0.1954, 0.8782, 0.1740, 0.2145, 0.8480]]),
 torch.float32)

##### 2. Perform a matrix multiplication on the tensor from Q1 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor with shape (1,7)
random_tensor2 = torch.rand(size=(1,7))
random_tensor2

tensor([[0.9218, 0.9914, 0.0693, 0.9899, 0.6978, 0.5739, 0.4093]])

In [28]:
# Transpose matrix (1,7)
random_tensor_T = random_tensor2.T

# Perform a matrix multiplication on the tensor in Q1 & Q2
tensor1 = torch.matmul(random_tensor,random_tensor_T)
print(tensor1) 
print(f"\nOutput shape: {tensor1.shape}")

tensor([[1.4604],
        [2.7057],
        [2.4358],
        [2.6602],
        [1.4092],
        [2.5080],
        [2.2686]])

Output shape: torch.Size([7, 1])


##### 3. Set the random seed to `0` and do exercises 2 & 3 over again.

In [29]:
import random

# Set the random seed
random_seed = 0
torch.manual_seed(seed=random_seed)
random_tensor_A = torch.rand(7,7)

# Set the random seed for the second matrix
random_seed = 0
torch.manual_seed(seed=random_seed)
random_tensor_B = torch.rand(1,7)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")


Tensor A:
tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

Tensor B:
tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])



In [30]:
# Transpose matrix (1,7)
random_tensor_BT = random_tensor_B.T

# Perform a matrix multiplication on the tensor in Q1 & Q2
tensor2 = torch.matmul(random_tensor_A, random_tensor_BT)
print(tensor2) 
print(f"\nOutput shape: {tensor2.shape}")

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

Output shape: torch.Size([7, 1])


##### 4. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one). If there is, set the GPU random seed to `1234`.

##### 5. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed).

In [39]:

import random

# Set the random seed
seed = 1234
torch.cuda.manual_seed(seed)
random_tensor_C = torch.rand(2,3)


# Set the random seed
seed = 1234
torch.cuda.manual_seed(seed)
random_tensor_D = torch.rand(2,3)

print(f"Tensor C:\n {random_tensor_C}\n")
print(f"Tensor D:\n {random_tensor_D}\n")


Tensor C:
 tensor([[0.8549, 0.5509, 0.2868],
        [0.2063, 0.4451, 0.3593]])

Tensor D:
 tensor([[0.7204, 0.0731, 0.9699],
        [0.1078, 0.8829, 0.4132]])



##### 6. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors)

In [40]:
# Transpose matrix (2,3)
random_tensor_DT = random_tensor_D.T

# Perform a matrix multiplication on the tensor in Q1 & Q2
tensor3 = torch.matmul(random_tensor_C, random_tensor_DT)
print(tensor3) 
print(f"\nOutput shape: {tensor3.shape}")

tensor([[0.9343, 0.6971],
        [0.5296, 0.5636]])

Output shape: torch.Size([2, 2])


##### 7. Find the maximum and minimum values of the output of 6.

In [41]:
print(f"Minimum: {tensor3.min()}")
print(f"Maximum: {tensor3.max()}")

Minimum: 0.5296216607093811
Maximum: 0.9343420267105103


##### 8. Find the maximum and minimum index values of the output of 6.

In [42]:
# Returns index of max and min values
print(f"Tensor\n{tensor3}")
print(f"Index where max value occurs: {tensor3.argmax()}")
print(f"Index where min value occurs: {tensor3.argmin()}")

Tensor
tensor([[0.9343, 0.6971],
        [0.5296, 0.5636]])
Index where max value occurs: 0
Index where min value occurs: 2


##### 9. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [47]:
##### 9. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.


import random

# Set the random seed
random_seed = 7
torch.manual_seed(seed=random_seed)
random_tensor_E = torch.rand(1,1,1,10)

# Remove 1s and retain the tensor shape (10)
random_tensor_E_squeezed = random_tensor_E.squeeze()

print(f"First tensor:\n {random_tensor_E}") 
print(f"\nFirst tensor shape:\n {random_tensor_E.shape}\n")
print(f"Second Tensor:\n {random_tensor_E_squeezed}\n") 
print(f"\nSecond tensor shape:\n {random_tensor_E_squeezed.shape}")

First tensor:
 tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])

First tensor shape:
 torch.Size([1, 1, 1, 10])

Second Tensor:
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])


Second tensor shape:
 torch.Size([10])
